---
galaxy_info:
  author: Lenny Shirley
  description: Obtains an OAuth2 API token for Ansible Automation Platform (Controller or Gateway).
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms: []
  galaxy_tags:
    - aap
    - controller
    - hub
    - eda
    - diagnostics
    - api
dependencies: []
...
