- hosts: testservers
  tasks:
  - name: Remove  telnet Package
    yum: name=telnet state=absent
  - name: Install SSSD
    yum: name=sssd state=installed
  - name: Install scl-utils
    yum: name=scl-utils state=installed
