- hosts: all
  tasks:
  - name: Copy multiple files in Ansible with different permissions
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
    with_items:
      - { src: '/home/sandy/Templates/test1',dest: '/tmp/devops_system1', mode: '0777'}
      - { src: '/home/sandy/Templates/test2',dest: '/tmp/devops_system2', mode: '0707'}
      - { src: '/home/sandy/Templates/test3',dest: '/tmp/devops_system3', mode: '0575'}
