- hosts: localhost
  tasks:
  - name: check file present or not
    stat:
     path: /home/sandy/simplefile.txt
    register: p
  - name: move file to folder
    command: mv /tmp/simplefile.txt /home/sandy
    when: p.stat.exists == False
     
