---
- name: Cleanup | Check for old SOS Reports # noqa: var-naming[no-role-prefix]
  ansible.builtin.find:
    paths: /var/tmp
    patterns: sosreport-*.tar.*
  register: __sos_reports

- name: Cleanup | Delete old SOS Reports (if any were found)
  loop: "{{ __sos_reports.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
...
