---
- name: Fetch | Find the generated SOS Report # noqa: var-naming[no-role-prefix]
  ansible.builtin.find:
    paths: /var/tmp
    patterns: sosreport-*.tar.xz
    age: -5m # Find reports created in the last 5 minutes to be safe
  register: __found_sos_report

- name: Fetch | Case folder block
  when: __found_sos_report.matched > 0
  vars:
    __dest_path: "{{ sos_report_dest }}/{{ inventory_hostname | lower | regex_replace('[^a-zA-Z0-9_-]', '-') }}"
  block:
    - name: Fetch | Ensure destination folder exists
      ansible.builtin.file:
        name: "{{ __dest_path }}"
        state: directory
        mode: "0777"
      delegate_to: localhost

    - name: Fetch | Fetch the SOS Report to the control node
      loop: "{{ __found_sos_report.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      become: true
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ __dest_path }}/"
        flat: true

    - name: Fetch | Build case_updates_needed variable # noqa: var-naming[no-role-prefix]
      loop: "{{ __found_sos_report.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      ansible.builtin.set_fact:
        case_updates_needed: >-
          {{ case_updates_needed | default([]) +
          [{
            'attachment': __dest_path ~ '/' ~ item.path | basename,
            'attachmentDescription': (
              "Gathered from '" ~ ansible_fqdn
              ~ "' using the 'infra.support_assist' Ansible Collection. Inventory Hostname: '"
              ~ inventory_hostname ~ "'"
            )
          }] }}
...
