---
- name: Ensure SOS report destination root exists on control node
  ansible.builtin.file:
    path: "{{ sos_report_dest }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  run_once: true

- name: Install
  ansible.builtin.include_tasks: install.yml

- name: Block
  block:
    - name: Generate
      ansible.builtin.include_tasks: generate.yml

    - name: Fetch
      ansible.builtin.include_tasks: fetch.yml

  always:
    - name: Cleanup
      when: sos_report_cleanup | bool
      ansible.builtin.include_tasks: cleanup.yml
...
