---
- name: Refresh Token | Print on screen role execution status.
  ansible.builtin.debug:
    msg:
      - "{{ rh_token_refresh_separator_char * (message_text | length + rh_token_refresh_default_message_padding) | int }}"
      - " {{ message_text }} "
      - "{{ rh_token_refresh_separator_char * (message_text | length + rh_token_refresh_default_message_padding) | int }}"
  vars:
    message_text: "Refreshing Red Hat Access Token via Offline Token"
  run_once: true

- name: "Refresh Token | Acquire New Red Hat SSO Access Token" # noqa: var-naming[no-role-prefix]
  ansible.builtin.uri:
    url: "{{ rh_api_token_url | default(rh_token_refresh_api_token_url) }}"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rh_token_refresh_api_offline_token | default(rh_token_refresh_api_offline_token) }}"
    return_content: true
    validate_certs: false
    status_code: 200
    use_proxy: "{{ rh_token_refresh_use_proxy | default(false) }}"
  register: __token_response
  no_log: "{{ rh_token_refresh_no_log }}" # <--- To keep sensitive values out of Ansible output logs
  environment:
    https_proxy: "{{ rh_token_refresh_http_proxy }}"
    http_proxy: "{{ rh_token_refresh_http_proxy }} "

- name: Refresh Token | Set access token fact
  ansible.builtin.set_fact:
    rh_token_refresh_api_access_token: "{{ __token_response.json.access_token }}"
  no_log: "{{ rh_token_refresh_no_log }}" # <--- To keep sensitive values out of Ansible output logs

- name: Refresh Token | Cache the new token and timestamp locally
  ansible.builtin.copy:
    content: |
      {
        "token": "{{ rh_token_refresh_api_access_token }}",
        "timestamp": {{ lookup('pipe', 'date +%s') }}
      }
    dest: "{{ rh_token_refresh_token_cache_file }}"
    mode: '0600' # Set secure permissions for the token file.
  no_log: "{{ rh_token_refresh_no_log }}" # <--- To keep sensitive values out of Ansible output logs

- name: Refresh Token | Print on screen role completion status.
  ansible.builtin.debug:
    msg:
      - "{{ rh_token_refresh_separator_char * (message_text | length + rh_token_refresh_default_message_padding) | int }}"
      - " {{ message_text }} "
      - "{{ rh_token_refresh_separator_char * (message_text | length + rh_token_refresh_default_message_padding) | int }}"
  vars:
    message_text: "Red Hat Access Token Refresh Completed Successfully"
  run_once: true
...
