# --- OCP Login Task File (Authentication)---
---
- name: Login | Print on screen login initiation status.
  ansible.builtin.debug:
    msg:
      - "{{ ocp_must_gather_separator_char * (message_text | length + ocp_must_gather_default_message_padding) | int }}"
      - " {{ message_text }} "
      - "{{ ocp_must_gather_separator_char * (message_text | length + ocp_must_gather_default_message_padding) | int }}"
  vars:
    message_text: "Initiating OpenShift Cluster Authentication Process"
  run_once: true

- name: Login | Logging log into an OCP cluster using the 'oc login' command # noqa: var-naming[no-role-prefix]
  ansible.builtin.command: >
    oc login
    --token={{ ocp_must_gather_token }}
    --server={{ ocp_must_gather_server_url }}
    {% if not ocp_must_gather_validate_ssl | bool %} --insecure-skip-tls-verify {% endif %}
  register: __oc_login_result
  changed_when: __oc_login_result.rc == 0
  failed_when: false

- name: Login | Verify 'oc' authentication # noqa: var-naming[no-role-prefix]
  ansible.builtin.command: oc whoami
  register: __oc_whoami
  changed_when: false
  failed_when: false

- name: Login | Assert successful authentication to OpenShift cluster
  ansible.builtin.assert:
    that:
      - __oc_login_result.rc == 0
      - __oc_whoami.rc == 0
    fail_msg: |
      FAILED! Oh. No! => Failed to verify OpenShift authentication using 'oc login' or 'oc whoami'.
      This is often caused by an expired token or incorrect API URL/validation setting.
      Login Error (if any): {{ __oc_login_result.stderr | default(__oc_login_result.stdout | default('No login output')) }}
      Whoami Error (if any): {{ __oc_whoami.stderr | default(__oc_whoami.stdout | default('No whoami output')) }}
    success_msg: "PASSED! Oh, Yes! => Authentication successful. Logged in as {{ __oc_whoami.stdout | default('User') }}."
  when: __oc_login_result is defined and __oc_whoami is defined

- name: Login | Print on screen authentication complete
  ansible.builtin.debug:
    msg:
      - "{{ ocp_must_gather_separator_char * (message_text | length + ocp_must_gather_default_message_padding) | int }}"
      - " {{ message_text }} "
      - "{{ ocp_must_gather_separator_char * (message_text | length + ocp_must_gather_default_message_padding) | int }}"
  vars:
    message_text: "OpenShift Cluster Authentication Completed Successfully"
  run_once: true
...
